name: Test AWS CLI with LocalStack

on:
  push:
    branches:
      - main

jobs:
  test-aws-cli:
    runs-on: ubuntu-latest

    steps:
      - name: Set up LocalStack
        run: docker run -d -e SERVICES=s3 -p 4566:4566 localstack/localstack

      - name: Wait for LocalStack to start
        run: sleep 10

      - name: Configure AWS CLI
        run: aws configure set default.s3.endpoint_url http://localhost:4566

      - name: Run AWS CLI commands
        run: |
          aws s3 ls
          aws s3 mb s3://test-bucket
          aws s3 cp file.txt s3://test-bucket/file.txt
