name: Validate-ElastAlert

on:
  push:
    branches: [ main, dev, preprod ]
  pull_request:
    branches: [ main, dev, preprod ]

jobs:
  validate-elastalert:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install elastalert
        # Add any other dependencies needed
        
    - name: Run ElastAlert validator
      run: elastalert-test-rule --config config.yaml --rules rules_folder
