name: Validate-YAML

on:
  push:
    branches: [main, dev, preprod]
  pull_request:
    branches: [main, dev, preprod]

jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate YAML file
        run: |
          yamllint -d "{extends: default, rules: {line-length: disable}}" configmap-vmalertrules.yaml
      # - uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.10'
      # - name: Install sqlvalidator
      #   run: pip install sqlvalidator
      # - name: Run Python script to validate YAML
      #   run: python .github/workflows/validate-alertrules.py
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sqlvalidator  # Install the required Python module
          
      - name: Run Shell Script
        run: |
          chmod +x .github/workflows/validate-alertrules.sh
          .github/workflows/validate-alertrules.sh
