name: Validate-ElastAlert

on:
  push:
    branches: [ main, dev, preprod ]
  pull_request:
    branches: [ main, dev, preprod ]

jobs:
  validate-elastalert:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Docker
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Build Docker image
      run: |
        docker build -t elastalert-image .
    
    - name: Run Docker container
      run: |
        docker run --name elastalert-container elastalert-image
    
    - name: Validate ElastAlert rules
      run: |
        docker exec elastalert-container elastalert-test-rule --config /path/to/your/config.yaml --rules /path/to/your/rules_folder
