name: Test AWS CLI with LocalStack

on:
  push:
    branches:
      - main

jobs:
  test-aws-cli:
    runs-on: ubuntu-latest

    steps:
      - name: Set up LocalStack
        run: |
          docker run -d -e SERVICES=s3 -p 4566:4566 localstack/localstack
          sleep 10  # Wait for LocalStack to start

      - name: Configure AWS CLI
        run: |
          aws configure set default.s3.endpoint_url http://localhost:4566
          aws configure set default.region us-east-1  # Set a default region

      - name: List S3 Buckets
        run: |
          aws s3 ls

      - name: Create S3 Bucket
        run: |
          aws s3 mb s3://test-bucket

      - name: Upload File to S3
        run: |
          echo "Hello, LocalStack!" > file.txt
          aws s3 cp file.txt s3://test-bucket/file.txt

      - name: Clean up
        run: |
          aws s3 rm s3://test-bucket/file.txt
          aws s3 rb s3://test-bucket --force
